all:
  children:
    vyos:
      children:
        starship:
          children:
            starship_main:
              hosts:
                ss_main_bash:
                  ansible_host: 10.9.100.5
                ss_main_1:
                  ansible_host: 10.9.100.5
                ss_main_2:
                  ansible_host: 10.9.1.2
            starship_backup:
              hosts:
                ss_backup_bash:
                  ansible_host: 10.9.100.5
                ss_backup_1:
                  ansible_host: 10.9.100.5
                ss_backup_2:
                  ansible_host: 10.9.1.3
        landmaster:
          children:
            landmaster_main:
              hosts:
                lm_main_bash:
                  ansible_host: 10.9.100.4
                lm_main_1:
                  ansible_host: 10.9.100.4
                lm_main_2:
                  ansible_host: 10.9.2.2
            landmaster_backup:
              hosts:
                lm_backup_bash:
                  ansible_host: 10.9.100.2
                lm_backup_1:
                  ansible_host: 10.9.100.2
                lm_backup_2:
                  ansible_host: 10.9.2.3
        arwing:
          children:
            arwing_main:
              hosts:
                ar_main_bash:
                  ansible_host: 10.9.100.3
                ar_main_1:
                  ansible_host: 10.9.100.3
                ar_main_2:
                  ansible_host: 10.9.3.4
