all:
  children:
    vyos:
      children:
        vyos-ss:
          children:
            vyos-ss-main:
              children:
                vyos-ss-main-bash:
                  hosts:
                    10.9.100.3
                vyos-ss-main-1:
                  hosts:
                    10.9.100.3
                vyos-ss-main-2:
                  hosts:
                    10.9.1.2
            vyos-ss-backup:
              children:
                vyos-ss-backup-bash:
                  hosts:
                    10.9.100.3
                vyos-ss-backup-1:
                  hosts:
                    10.9.100.3
                vyos-ss-backup-2:
                  hosts:
                    10.9.1.3
        vyos-lm:
          children:
            vyos-lm-main:
              children:
                vyos-lm-main-bash:
                  hosts:
                    10.9.100.4
                vyos-lm-main-1:
                  hosts:
                    10.9.100.4
                vyos-lm-main-2:
                  hosts:
                    10.9.2.2
            vyos-lm-backup:
              children:
                vyos-lm-backup-bash:
                  hosts:
                    10.9.100.4
                vyos-lm-backup-1:
                  hosts:
                    10.9.100.4
                vyos-lm-backup-2:
                  hosts:
                    10.9.2.3
        vyos-ar:
          children:
            vyos-ar-bash:
              hosts:
                10.9.2.5:
            vyos-ar-1:
              hosts:
                10.9.100.4
            vyos-ar-2:
              hosts:
                10.9.2.5
