---
- hosts: "{{ node }}_bash"
  vars_files: vault.yml
  gather_facts: 'no'
  roles:
    - bashrc

- hosts: "{{ node }}_1"
  connection: network_cli
  vars_files: vault.yml
  gather_facts: 'no'
  roles:
    - conf-system
    - fw-groups
    - fw-rules
    - interfaces
    - fw-wan
    - vrrp
    - fw-zones
    - nat

- hosts: "{{ node }}_2"
  connection: network_cli
  vars_files: vault.yml
  gather_facts: 'no'
  roles:
    - del-ci-if
