---
- name: set zone based fw
  vyos_config:
    lines:
    - set firewall zone WAN default-action 'drop'
    - set firewall zone WAN interface 'eth0'
    - set firewall zone WAN from vlan2 firewall name 'lan-wan'
    - set firewall zone WAN from vlan4 firewall name 'lan-wan'
    - set firewall zone WAN from vlan8 firewall name 'lan-wan'
    - set firewall zone WAN from vlan9 firewall name 'lan-wan'
    - set firewall zone WAN from vlan11 firewall name 'lan-wan'

    - set firewall zone vlan9 default-action 'drop'
    - set firewall zone vlan9 from WAN firewall name 'wan-lan'
    - set firewall zone vlan9 from vlan8 firewall name 'vlan8-vlan9'
    - set firewall zone vlan9 from vlan2 firewall name 'vlan2-vlan9'
    - set firewall zone vlan9 from vlan4 firewall name 'vlan4-vlan9'
    - set firewall zone vlan9 from vlan11 firewall name 'vlan11-vlan9'
    - set firewall zone vlan9 interface 'eth1.9v1v4'
    - set firewall zone vlan9 interface 'eth1.9'

    - set firewall zone vlan8 default-action 'drop'
    - set firewall zone vlan8 description 'media-server'
    - set firewall zone vlan8 from WAN firewall name 'wan-lan'
    - set firewall zone vlan8 from vlan9 firewall name 'vlan9-vlan8'
    - set firewall zone vlan8 from vlan2 firewall name 'vlan2-vlan8'
    - set firewall zone vlan8 from vlan4 firewall name 'vlan4-vlan8'
    - set firewall zone vlan8 from vlan11 firewall name 'vlan11-vlan8'
    - set firewall zone vlan8 interface 'eth1.8v1v4'
    - set firewall zone vlan8 interface 'eth1.8'

    - set firewall zone vlan2 default-action 'drop'
    - set firewall zone vlan2 from WAN firewall name 'wan-lan'
    - set firewall zone vlan2 from vlan9 firewall name 'vlan9-vlan2'
    - set firewall zone vlan2 from vlan8 firewall name 'vlan8-vlan2'
    - set firewall zone vlan2 from vlan11 firewall name 'vlan11-vlan2'
    - set firewall zone vlan2 from vlan4 firewall name 'vlan4-vlan2'
    - set firewall zone vlan2 interface 'eth1.2'
    - set firewall zone vlan2 interface 'eth1.2v1v4'

    - set firewall zone vlan11 default-action 'drop'
    - set firewall zone vlan11 from WAN firewall name 'wan-lan'
    - set firewall zone vlan11 from vlan2 firewall name 'vlan2-vlan11'
    - set firewall zone vlan11 from vlan8 firewall name 'vlan8-vlan11'
    - set firewall zone vlan11 interface 'eth1.11'
    - set firewall zone vlan11 interface 'eth1.11v1v4'

    - set firewall zone vlan4 default-action 'drop'
    - set firewall zone vlan4 from WAN firewall name 'wan-lan'
    - set firewall zone vlan4 from vlan9 firewall name 'vlan9-vlan4'
    - set firewall zone vlan4 from vlan8 firewall name 'vlan8-vlan4'
    - set firewall zone vlan4 from vlan2 firewall name 'vlan2-vlan4'
    - set firewall zone vlan4 interface 'eth1.4v1v4'
    - set firewall zone vlan4 interface 'eth1.4'
