---
- name: Configure {{ vyos_hostname }} system settings
  vyos_config:
    lines:
    - set service ssh port '22'
    - set system config-management commit-revisions '100'
    - set system conntrack modules ftp
    - set system conntrack modules h323
    - set system conntrack modules nfs
    - set system conntrack modules pptp
    - set system conntrack modules sip
    - set system conntrack modules sqlnet
    - set system conntrack modules tftp
    - set system console device ttyS0 speed '115200'
    - set system host-name '{{ vyos_hostname }}'
    - set system login user vyos authentication public-keys houndsolo@archlinux key 'AAAAB3NzaC1yc2EAAAADAQABAAAEAQCqiUCaNVQF7wLvWIiGB/olMnaKeElP4zLJndHwj0OIbBCpN4zzEXDOWoEdkGSzShlKlXzk/q+0Bi2KNyjqu+66UlnLAKOtw1t4L+iDXGP1P/27ah/azP+eDzjOuBXTtiO7gdjSGoma5jRLhyR5Le/OOYZKnvNWkzsNkaB0QdCKD56uYGuw06FIDSHsTHKzC0lu7Ma9Rjot5M3zW4zTDahqh5Uh9INhr7W1hMCkKbHmHUne0A9rVAkj+jd2IUqfH4amCHjB/zW3lfcAiLV4UOUaNh1LWr4g4qRGBdUTes7MgblYQw6JWxXzzM/4b2mbM7nFzHLr9LmkQcGC4JU2QTJc3kHL/YwsxzRPJcJXpPMmMj0ndSnJYNsEstax4NKtCDm/5MAOVGi8vaIrZ+Gkt8ESMpwvNH/NI8ODTblSxcPu92bAFkYGlc9/uOmmY1i5iATHp/juGt0+hj6jZJJ+4s2y+NFNv67jXrde/yAN9PW71MbKDYXBRh9eVT9RRcj0vp8jR3e8yKnHL8dHtzxoowd37zIa5iX4iJQ9OToAcnql4jEzOUQhzGaGng6FRDOgDzdSVu9dSGegVl2MhFmZABwrBHuNhIYuFQcN53AxAUEOGIq+cELh/1JsaQQy+rqg5pEYLw3NjMnH/ngIKXOG/HHpamM6ueYwhQ7jiR7VkHqjXbALGKKdgMovzdc/d7N79+8/PHZthzyMBtnNxxJtH4a5d+qEj6aFmKbJ+e5NGyt8tJXAAO/QIsXq5TIstrMqLAkbYbcGxBe8YWWcnmWE69nVzKoA5mSNq+2pX3Q+0fASbOMLROGBUaoqJISk9MoxOZ3xrvMxQ54dioYBbqSmak+GoJJ9eM6lGCcytrAqgTKk8CuJA+WZRI2xqnFThhuvj4mv1EGvZ5k/tKTkascwpxDus0sYZGQYt2uxPQ6oq7YQsWXfxjFlJszMP4/9FJp7OhF5K4e44ImEG6ie/wo16Ny0kZAhS2Mqt5+W8Cfvosbr9MjUmSWlnrBgoMTMggCx8JW5pMR2b+4V9DNX/5YQ4+DbmjeWnxHgDuXVaabxFg0TpAwYXtFrzNrEeBONQNW0yMStbShtnGkMnYjFnCWGd7pbmNdOTB/igrCUc5kkZS9kKKVCYcDVJoY7iwSxR2LXorjKnPR88du+gRXWcppJBWTg5mRq7GSX9xLKS04GqBNPL+82mKLXJXNyO/QWEOTjHHiq+CuJyg/r0eKRSGd6eOY/w76dHmhrQz2HdguDIAVTHVDKsLYU9wLzAyQbC019I2T1Vc6zCi7dwTU9fD3A4E2Oa2iFm97kpiksmUSwEEWpOcke49NBzBrmu8zeNYdGh33o4mlxp8UbdiLawODfm9rv'
    - set system login user vyos authentication public-keys houndsolo@archlinux type 'ssh-rsa'
    - set system login user vyos authentication public-keys houndsolo@msi key 'AAAAB3NzaC1yc2EAAAADAQABAAAEAQCuu5wm/71h2spb4HYRcdpG99SKDrYz+cEIdsZMErrEp0Oci7m8YpYWP0rWjCk+wiJf708ucZRhOBq0KyyaPMGveRlwVPV/47r1VnR4P3P6Bv342LPByXsePVlbGdhOHbkEiov7EtecGbhHZG8iGZ/a1SHJv39tU7gbaauzQVd8cZiGVV+enge7qCASldqBENArqrVy0LIErF2bbW2+Ivf89c87NGJbVjNHgylbvpvdXZb1wlUUAQtkKfGPZCt+Qgs9tjAvWuTYzvrjLO71Fgs6zniQ80Enx7G7wG9qKxBDYFftmNOFZLiIhGJ8bpswK5ubFBlloCnTPx3t/UYR39420hZO8YFsvFIvDspFiKM75KY1g017pf1M5ufpM29u322nhjduuf7L5QvAIbUDfgOMIDw5dxWHz/uay7wv8jjOcT0t734QSjspCgIPTnmkMNbwW36j7xMdrpL5d0g+HtXYaPsUjxxrAMG29p8VGRymXlLKgLergaeBnyi9qlV4nVnT5u1IJwIth5HpnnEfu6W3uYqxbz0R+qHhmZgy6y7iKWTvbheVuvl/kdMCMNEAv1OfH9OWSP8muDijuKLRHvfwPvnqjlGa05gc6prsLsJUicZM4aqBbJ7m4VYeM8RFWi7MCEEO66/I4BYB11FAALlvZKdt66xdEpkxBktfuPQSGrgJXbmVoC71uRm6329nUcf36JSmsMYMLj40vSyFPEyll3GRVxifVq24LpddGSgio0hEapntp/ZpktshOnj713NOC7JUCWG4YeUL6/KJUNxDBK51HeGUjmnaAMKybqeMeyvrF/tVGlHivxTwkWecazoq8a70KJbmE6MmT1KHqVmpUlW1eVJy9vGpERxNnmeoJ25xzXgfyp0fIfVpQWDsqGGxjPD0cgMESl27Ra2rlgMgYcmMOIl4qnz7fODKgYdBXFKnzel6Za7ISCnIALR1Ry6Qg9lCWOK/Xy6OvHTyew94KV+izwSRzHa3BA+o6NeRzxGQfI47B27Xm43gEM/pXnxnCACA1O2Lk7abd8gQmi4H8M5F59UwyuRyQSlEDbNnpdynwVsPvowYy8gjruNIv9cvsFBwrgWSWFJmB9LI6lOUSTjDk4nsDCU4El69TJiAuV5miniS+qrPOjNlh7CCYSdbQcgo8d6jOe0BFAH9NbRull7vv79BSPin+Gc7ppwsErbXPbBJrD4iumQ75eHuvDdtX3+kyLcHtlLAfHN4RmieCtF6cKMQHMkaFNBkEF3i+Fdebjk08CawP6Yvogm0z3Lqkrv/HSiqB/wEO0DiPyDzGgMNhHbJ8O1RcEQi/E/dfmeWtfTQwa+0tsNjxbSkxPeXUfo2Uk9k+TzMnD8I0tfN'
    - set system login user vyos authentication public-keys houndsolo@msi type 'ssh-rsa'
    - delete system name-server
    - set system ntp server time1.vyos.net
    - set system ntp server time2.vyos.net
    - set system ntp server time3.vyos.net
    - set system syslog global facility all level 'info'
    - set system syslog global facility protocols level 'debug'
  register: firstout

- name: print first out
  debug:
    var: firstout.filtered
- name: change Password for User vyos
  vyos.vyos.vyos_user:
    name: vyos
    configured_password: '{{ vyos_password }}'
    update_password: always
    state: present
