---
- name: configure nat
  vyos_config:
    lines:
    - set nat source rule 100 outbound-interface 'eth0'
    - set nat source rule 100 source address '10.9.0.0/16'
    - set nat source rule 100 translation address 'masquerade'
    - set nat source rule 101 outbound-interface 'eth0'
    - set nat source rule 101 source address '10.2.0.0/16'
    - set nat source rule 101 translation address 'masquerade'
    - set nat source rule 102 outbound-interface 'eth0'
    - set nat source rule 102 source address '10.4.0.0/16'
    - set nat source rule 102 translation address 'masquerade'
    - set nat source rule 103 outbound-interface 'eth0'
    - set nat source rule 103 source address '10.11.0.0/16'
    - set nat source rule 103 translation address 'masquerade'
    - set nat source rule 108 outbound-interface 'eth0'
    - set nat source rule 108 source address '10.8.0.0/16'
    - set nat source rule 108 translation address 'masquerade'
