---
- name: set up interfaces
  vyos_l3_interfaces:
    config:
    - name: eth0
      ipv4:
      - address: dhcp
    - name: eth1
      vifs:
      - vlan_id: 2
        ipv4:
        - address: 10.2.{{ octet3 }}.{{ vyos_id }}/20
      - vlan_id: 4
        ipv4:
        - address: 10.4.{{ octet3 }}.{{ vyos_id }}/24
        - address: 10.4.0.104/24
      - vlan_id: 8
        ipv4:
        - address: 10.8.{{ octet3 }}.{{ vyos_id }}/16
      - vlan_id: 9
        ipv4:
        - address: 10.9.{{ octet3 }}.{{ vyos_id }}/16
      - vlan_id: 11
        ipv4:
        - address: 10.11.{{ octet3 }}.{{ vyos_id }}/16
    state: overridden
